### ISSUE TITLE
[Bug] Permission Denied - exited code 0

### ISSUE THREAD

**Issue by samarthkharbanda** [Suwayomi/docker-tachidesk#103]
Issue with running tachidesk container 

Error Permission denied
[_suwayomi-tachidesk-suwayomi-1_logs.txt](https://github.com/user-attachments/files/16816990/_suwayomi-tachidesk-suwayomi-1_logs.txt)

<DockerCompose I am using is Below>

services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:stable
    environment:
      - TZ=Etc/UTC 
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=http://flaresolverr:8191
      - BIND_PORT=4567
      - BASIC_AUTH_ENABLED=true
      - BASIC_AUTH_USERNAME=manga
      - BASIC_AUTH_PASSWORD=hello123
    volumes:
      - /home/<my username>/DockerApps/Tachidesk:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "4567:4567"
    restart: on-failure:3
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Etc/UTC 
    ports:
      - "8191:8191"
    restart: unless-stopped

**Comment by mBuschauer** [comment]
If you're running on Linux, this might be a permissions issue with the volume you're using. I had a similar problem and fixed it by adjusting the ownership of the directory where the Tachidesk data is stored.

You can try running the following command to change the ownership of the folder to match the suwayomi container's user (usually 1000:100 corresponds to user:users):

```bash
chown -R 1000:100 data/
```

Make sure you run this on the host machine where the data file is, and it should resolve the "Permission denied" error.

**Comment by samarthkharbanda** [comment]
Started working after using above command as well as passing puid and guid environment variable in docker compose of tachidesk
