### ISSUE TITLE
Java 11 base image

### ISSUE THREAD

**Issue by renjfk** [Suwayomi/docker-tachidesk#104]
Hi,

Is there any reason why the base image is Java 11? The latest Java LTS is Java 21 and it outperforms Java 11 in every aspect so it's a bit wasteful for it to be Java 11.

**Comment by Syer10** [comment]
I haven't gotten around to updating the base image, as long as the PR tests pass it would likely work out of the box though

**Comment by renjfk** [comment]
This is probably out of context, but even though the project is scaled really small, it would be much better if the container image was built with [Jib](https://github.com/GoogleContainerTools/jib), as it integrates perfectly with Gradle and outputs really optimized images (e.g. almost half the size compared to what Docker builds) for Java applications.

**Comment by Syer10** [comment]
I've updated the base image to 21.
I've also taken a look at Jib, I think I will have to pass on it. We use a bunch of docker configuration parameters and Jib seems to be limiting in that aspect.
