### ISSUE TITLE
docker-compose variable for custom download location

### ISSUE THREAD

**Issue by iafuad** [Suwayomi/docker-tachidesk#105]
I know we can already do it by modifying the `server.conf` file or through the webui but it would be pretty convenient if you also map a variable for custom download location in the docker-compose. We already have variables for all the other important settings, why leave this out?

**Comment by Syer10** [comment]
See https://github.com/Suwayomi/docker-tachidesk/issues/68, I also just added a note about this in the README https://github.com/Suwayomi/docker-tachidesk/blob/main/README.md#downloads-folder
