### ISSUE TITLE
Compose formatting and Permissions error

### ISSUE THREAD

**Issue by sunjam** [Suwayomi/docker-tachidesk#15]
Within your [compose file](https://github.com/Suwayomi/docker-tachidesk/blob/main/compose.yml) there is a formatting error.  There is incorrect odd number spacing starting with the line:

`   custom_network1:`

Left as-is it fails with the error:
```
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 4, column 3
expected <block end>, but found '<block mapping start>'
  in "./docker-compose.yml", line 20, column 4
```

and a hyphen appears to be missing from the start of `           gateway: 172.22.2.1  `

The edited script returns an error related to `networks:`
```
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 7, column 15
```
> I added UID 1000 and GID 1000 envs, and made sure that folder chosen had permissions with chown 1000 <folder_path> . Works like a charm.  #5 

What would be the best way to permanently resolve this within the compose file?  You could define `user` or `.env` in order to avoid this.

**Comment by arbuilder** [comment]
> Left as-is it fails with the error:

Thanks fixed it, can u check again to see if it works now

> What would be the best way to permanently resolve this within the compose file? You could define `user` or `.env` in order to avoid this.

I run tachidesk jar as non root user for security so few people have issues regarding permissions. I  had created a test docker image based on `user` but only one person tested it . Without majority of the people testing it i cant use that for build as it might create permission issue for majority of people who doestn't have issues right now and lose access to their already downloaded manga.
