### ISSUE TITLE
proxy not work

### ISSUE THREAD

**Issue by MvCraK** [Suwayomi/docker-tachidesk#16]
i set socks5 proxy in server.conf，but not work

**Comment by arbuilder** [comment]
can u share your docker compose

**Comment by arbuilder** [comment]
in generel docker containers are isolated so u cannot copy same network configuration of tachidesk running on host. U have to use google search for specific use case.

I am closing this as i don't know the details of your host os , proxy server and compose

**Comment by tontyoutoure** [comment]
I'm not sure about your situation, but I'll tell what works for me:

In your proxy application, activate option like "allow connection from LAN"
then fill the LAN ip address in server.socksProxyHost, maybe something like "192.168.xxx.xxx"
