### ISSUE TITLE
Configuration-File changes not affecting

### ISSUE THREAD

**Issue by Zaryu** [Suwayomi/docker-tachidesk#23]
The changes in configuration file in the docker version are not affecting anything, like port changes or authentication.

Double checked and the changes are affecting the file in the volume, but not the server, that should catch the config changes.

**Comment by arbuilder** [comment]
> like port change and authentication

port change and authentication works for me by editing server..conf file is used  ghcr.io/suwayomi/tachidesk:latest for testing

here is my server.conf file

```
# Server ip and port bindings
server.ip = "0.0.0.0"
server.port = 4568

# Socks5 proxy
server.socksProxy = false
server.socksProxyHost = ""
server.socksProxyPort = ""

# misc
server.debugLogsEnabled = true
server.systemTrayEnabled = false

# webUI
server.webUIEnabled = true
server.initialOpenInBrowserEnabled = false
server.webUIInterface = "browser"
server.electronPath = ""

# Auth
server.basicAuthEnabled = true
server.basicAuthUsername = "user1234"
server.basicAuthPassword = "password1234"
```

and my docker command 
```
docker run -d --rm -p 4568:4568 -v /home/$USER/tachidesk:/./home/suwayomi/.local/share/
Tachidesk ghcr.io/suwayomi/tachidesk
```

just to be sure u restarted the container after changing the values in server.conf right ?

**Comment by SilverServer34** [comment]
I have the same situation, I tried to remove the container and recreate it from scratch but it ignores the Auth or even the webui enabled = false. Am I missing something?
