### ISSUE TITLE
[Bug] Can't run docker image in Portainer

### ISSUE THREAD

**Issue by machine-doll** [Suwayomi/docker-tachidesk#24]
## Device information
- Tachidesk version: latest docker image  
- Server Operating System: Portainer 2.0.1 on OpenWRT 21.02  
- Server Desktop Environment: N/A  
- Server JVM version: none  
- Client Operating System: Windows 11  
- Client Web Browser: Edge 105.0  

## Steps to reproduce
1. First Step  
    Open Portainer, click `Create container`, switch to `Advanced mode`, input `ghcr.io/suwayomi/tachidesk` in image configuration. 
2. Second Step
    Click `Deploy the container`
### Expected behavior
The container is deployed and is able to run. 

### Actual behavior
A lot of different version of docker images are pulled, none of them are deployed. 

## Other details
The kernel version of this OpenWRT device is 5.4 and it is from Armbian. The CPU arch is ARM64. The docker is from package `luci-app-docker`. 
I've tested some other docker images, and they are able to deploy and run in this way.

**Comment by Robonau** [comment]
have you added ghcr.io as a registry? you will need to use said registry not docker.io
did you fill in all the necessary options for tachi to run in docker (environment variables, volumes, ports, etc)?
cause its working fine for me

**Comment by arbuilder** [comment]
@machine-doll can u share the logs?

**Comment by mistercorea** [comment]
I am having similar issue 

```
version: '3.7'

services:

  tachidesk-docker:
    image: ghcr.io/suwayomi/tachidesk
    container_name: tachidesk-docker
    environment:
      - PUID=1000 # ( dont change, require uid to be 1000 )
      - PGID=1000 # ( dont change, require gid to be 1000 )
      - TZ=UTC # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - LOGGING=file
    volumes:
      - /volume1/docker/tachidesk/docker-config/tachidesk:/home/suwayomi/.local/share/Tachidesk # edit <path to folder> to your mapped folder
      #- /volume1/myLand/books/comics/webtoon:/home/suwayomi/.local/share/Tachidesk/downloads
    ports:
      - "4567:4567"
    restart: on-failure:3
```

log
```
/home/suwayomi/startup/startup_script.sh: 21: cannot create /home/suwayomi/.local/share/Tachidesk/logfile.log: Permission denied
                                                                ************README***********
-> It is essential that u read readme for ghcr.io/suwayomi/tachidesk before running this container
-> Readme for ghcr.io/suwayomi/tachidesk is available at https://github.com/suwayomi/docker-tachidesk 
                                                                *****************************
Tachidesk data location inside the container -> /home/suwayomi/.local/share/Tachidesk
The server is running by default configuration on  http://localhost:4567
log file location inside the container -> /home/suwayomi/.local/share/Tachidesk/logfile.log
/home/suwayomi/startup/startup_script.sh: 21: cannot create /home/suwayomi/.local/share/Tachidesk/logfile.log: Permission denied
                                                                ************README***********
-> It is essential that u read readme for ghcr.io/suwayomi/tachidesk before running this container
-> Readme for ghcr.io/suwayomi/tachidesk is available at https://github.com/suwayomi/docker-tachidesk 
                                                                *****************************
Tachidesk data location inside the container -> /home/suwayomi/.local/share/Tachidesk
The server is running by default configuration on  http://localhost:4567
log file location inside the container -> /home/suwayomi/.local/share/Tachidesk/logfile.log
                                                                ************README***********
/home/suwayomi/startup/startup_script.sh: 21: cannot create /home/suwayomi/.local/share/Tachidesk/logfile.log: Permission denied
-> It is essential that u read readme for ghcr.io/suwayomi/tachidesk before running this container
-> Readme for ghcr.io/suwayomi/tachidesk is available at https://github.com/suwayomi/docker-tachidesk 
                                                                *****************************
Tachidesk data location inside the container -> /home/suwayomi/.local/share/Tachidesk
The server is running by default configuration on  http://localhost:4567
log file location inside the container -> /home/suwayomi/.local/share/Tachidesk/logfile.log
                                                                ************README***********
-> It is essential that u read readme for ghcr.io/suwayomi/tachidesk before running this container
-> Readme for ghcr.io/suwayomi/tachidesk is available at https://github.com/suwayomi/docker-tachidesk 
                                                                *****************************
Tachidesk data location inside the container -> /home/suwayomi/.local/share/Tachidesk
The server is running by default configuration on  http://localhost:4567
log file location inside the container -> /home/suwayomi/.local/share/Tachidesk/logfile.log
/home/suwayomi/startup/startup_script.sh: 21: cannot create /home/suwayomi/.local/share/Tachidesk/logfile.log: Permission denied
```

**Comment by AkazaRenn** [comment]
I had to `chmod 777` to the host folder (`/volume1/docker/tachidesk/docker-config/tachidesk` for you) to get it working, overkill for sure but works.

**Comment by hakkabara** [comment]
> I had to `chmod 777` to the host folder (`/volume1/docker/tachidesk/docker-config/tachidesk` for you) to get it working, overkill for sure but works.

Just give the volume folder on your host:
``
chown -R 1000:1000 /your/folder/
``

better than 777....

keep safe ;)

**Comment by Syer10** [comment]
Closing old issues due to container rewrite, its may be fixed in the preview tag. Re-open if its not.

**Comment by RhanCandia** [comment]
> Closing old issues due to container rewrite, its may be fixed in the preview tag. Re-open if its not.

Doesn't seem to work still. I tried to set up one now using the peview tag but I still got Pemission Denied.



> > I had to `chmod 777` to the host folder (`/volume1/docker/tachidesk/docker-config/tachidesk` for you) to get it working, overkill for sure but works.
> 
> Just give the volume folder on your host: `chown -R 1000:1000 /your/folder/`
> 
> better than 777....
> 
> keep safe ;)

It worked when I did this for the bound volume.
