### ISSUE TITLE
Add a link to /home/suwayomi/.java/.userPrefs in /home/suwayomi/.local/share/Tachidesk

### ISSUE THREAD

**Issue by Syer10** [Suwayomi/docker-tachidesk#39]
Tachidesk uses Preferences to store certain things like source settings and cookies. Adding a shortcut to `/home/suwayomi/.java/.userPrefs` in the container will allow them to be saved when the container is shut-down, without an extra volume configuration.

**Comment by nogweii** [comment]
I'm going to explore this a little more, but according to the [Oracle JDK docs](https://docs.oracle.com/en/java/javase/11/core/preferences-api1.html#GUID-2DAC3DD0-993A-41A8-8CDC-F8E3A72E1AE3__SECTION_KWW_Z1P_S3B), we can override that path with a custom one by defining `java.util.prefs.userRoot`.

**Comment by Syer10** [comment]
Fixed by https://github.com/Suwayomi/Tachidesk-Server/pull/722
