### ISSUE TITLE
UNRAID: Download list retention and Leftover files in tmp directory after converted into CBZ

### ISSUE THREAD

**Issue by soldius** [Suwayomi/docker-tachidesk#40]
I am running the docker preview channel in a UNRAID server. After some troubleshooting to determine why the Tachidesk container is filling up my docker.img, I found that there is leftover data and an unmapped directory within the container.

Current behavior: it downloads the series to a `/tmp/Tachidesk/Manga-cache` in the root of the docker.img. 

The download structure is: Manga-cache/ExtensionName/SeriesName/Chapter

It downloads in images format for each chapter, then package it into a CBZ and put it in the correct Library volume (as mapped in the container). However, it leaves the image files behind and this is the reason why it is filling up the docker.img.

I created separate volume mapping for this in case anyone needs it:
![image](https://github.com/Suwayomi/docker-tachidesk/assets/44028743/c526c264-1f84-45a3-bc93-ed7e9be1b351)

This resolves the docker.img from filling up, but I still have to manually delete those leftover image files :/

I see that it also creates other things inside the /tmp folder so I am not sure if I should just map the /tmp instead of the individual mapping like above:
![image](https://github.com/Suwayomi/docker-tachidesk/assets/44028743/7df7f91a-8369-4fda-9ecc-7454c615a8de)

Also, throughout this process of turning off and on the container... I notice that the download list is not retained. I would have to add the downloads again each time. Not sure how/where this retention is mapped.

**Comment by nogweii** [comment]
> Current behavior: it downloads the series to a /tmp/Tachidesk/Manga-cache in the root of the docker.img.

That is because the server code currently is configured to use `java.io.tmpdir` to determine the location of where to store temporary data. We can add an environment variable to configure this.

> I notice that the download list is not retained. I would have to add the downloads again each time.

See #39 for why that's happening.

**Comment by soldius** [comment]
I tried to map `/home/suwayomi/.java/.userPrefs` but it still does not save my download list. :(

**Comment by Syer10** [comment]
The downloader queue is stored in memory, its intentional that its not persistent across restarts
