### ISSUE TITLE
[Request] Create new environment variables for new config file options in starting from preview v0.7.0-r1369

### ISSUE THREAD

**Issue by hikashin86** [Suwayomi/docker-tachidesk#55]
Requesting an environment variable for the two new options in config file:

"server.excludeEntryWithUnreadChapters" and "server.autoDownloadAheadLimit"

**Comment by vodkapmp** [comment]
~~At least the first one is implemented in #46.
server.excludeEntryWithUnreadChapters = UPDATE_EXCLUDE_UNREAD~~

Edit: nevermind I had misred the changes.
