### ISSUE TITLE
Does not save data

### ISSUE THREAD

**Issue by alexanderchacon** [Suwayomi/docker-tachidesk#56]
Hello! 

I have installed Tachidesk and it is working but it is not saving the sources and downloaded mangas, any idea?

**Comment by Syer10** [comment]
Make sure you are adding a volume(-v) to tell Tachidesk where to save data `docker run -p 127.0.0.1:4567:4567 -v <folder path>:/./home/suwayomi/.local/share/Tachidesk ghcr.io/suwayomi/tachidesk`
