### ISSUE TITLE
How to load/download extension?

### ISSUE THREAD

**Issue by linonetwo** [Suwayomi/docker-tachidesk#59]
Hi, I add some apk download from https://tachiyomi.org/extensions/ , and restart the docker, but it is not loading then as source.

![截屏2023-10-12 20 49 13](https://github.com/Suwayomi/docker-tachidesk/assets/3746270/4cfefbf4-7a63-460e-a893-85e500b4788f)

Directly download extension in /extensions is not working, it is always Downloading.
I also try add socks5 proxy, but it doesn't work too.
![截屏2023-10-12 20 49 25](https://github.com/Suwayomi/docker-tachidesk/assets/3746270/254f500d-fb77-4349-982c-45b855950ad1)

I tried restart/recreate container, not working.

I also try put some comic into /local folder, and it successfully show in the local source, so docker deployment is fine. (because I set the bind volume `/run/desktop/mnt/host/d/Tachidesk-Comic:/home/suwayomi/.local/share/Tachidesk`)

---

The log

```log
13:02:56.240 [DefaultDispatcher-worker-1] [1;31mERROR[0;39m suwayomi.tachidesk.manga.impl.extension.github.ExtensionGithubApi - Failed to get extensions from GitHub
java.net.ConnectException: Failed to connect to raw.githubusercontent.com/0.0.0.0:443
	at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:256)
	at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:128)
	at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:138)
```

suggest that proxy setting in docker env is not used by container.

Also in docker 

```
root@e6b56e6ed0c8:/home/suwayomi# ping raw.githubusercontent.com
PING raw.githubusercontent.com (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.915 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.035 ms
```

**Comment by linonetwo** [comment]
This works:


-- | --
SOCKS_PROXY_HOST | host.docker.internal



I think this should be in the doc...

To access socks5 in host network, you need to use `host.docker.internal`

---

Update: this is not working, still getting `Failed to connect to raw.githubusercontent.com/0.0.0.0:443`

**Comment by Syer10** [comment]
You need to use the api to manually install extensions, go to the extensions menu in WebUI and click the plus button at the top left to install them.

**Comment by linonetwo** [comment]
@Syer10 Thank you, this is the way to install .apk that I don't know before. 

I reopen the issue because I found even network error is gone, but clicking "install" button is still not working.

I will try install from apk now.

**Comment by linonetwo** [comment]
<img width="1747" alt="截屏2023-10-12 21 45 37" src="https://github.com/Suwayomi/docker-tachidesk/assets/3746270/c294164c-42a9-4e31-b58e-ca3fcb1fb397">

Install from apk works, thank you for quick response!

P.S. I still wondering how to make socks5 work...

**Comment by linonetwo** [comment]
Without a working socks5 proxy, many source is not working, I can open a new issue about this.

**Comment by Yuhyeong** [comment]
哥们，咱俩问题一样。我也在配sokcs，但是感觉没什么用

**Comment by linonetwo** [comment]
我不看漫画了，玩赛博朋克2077了
