### ISSUE TITLE
Reverse proxyed to tachidesk

### ISSUE THREAD

**Issue by duanyu5871** [Suwayomi/docker-tachidesk#64]
Is there any methods to reverse proxy to tachidesk with sub path. 
For example, tachidesk is running on port 4567, and can be accessed with localhost:4567
When I tried to reverse proxy to port 4567 with sub path like follow:
```
location /tachidesk {
        proxy_pass http://localhost:4567;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-for $remote_addr;
	proxy_set_header X-Scheme $scheme;
    }
```
Nothing can work because with 404 error, because all web path don't have prefix in URL.
![image](https://github.com/Suwayomi/docker-tachidesk/assets/15108185/ca48274b-84bf-418a-b1f4-7f2f87ca3d24)

**Comment by Robonau** [comment]
that will also proxy to `http://localhost:4567/tachidesk/...` no?
cause you aren't rewriting the url


just in general you are probably better off using subdomains than sub paths
ya wont ever run in to a service that cant deal with a subdomain
