### ISSUE TITLE
Armv8 can not ADD extensions.

### ISSUE THREAD

**Issue by hanke2254** [Suwayomi/docker-tachidesk#66]
Device：Synology DS420j，CPU：RTD1296，MEM：1G DDR
Docker （docker pull ghcr.io/suwayomi/tachidesk:v0.7.0-r1439）

**Comment by Syer10** [comment]
Use the preview tag and set the `DEBUG` environment variable to true.
The paste the logs that get outputted here so we can actually debug your issue.

**Comment by hanke2254** [comment]
您好，您的邮件我们已经收到，我们将尽快为您处理。感谢您对我们的支持。---------------------------------------------------------------------acaia中国售后服务技术中心

**Comment by hanke2254** [comment]
OK.Iwill.
Thank you.

**Comment by hanke2254** [comment]
The preview is ok.Thanks.

**Comment by hanke2254** [comment]
A new discovery,
SSH DSM IP
-------
sudo vi /etc/hosts
185.199.111.133 raw.githubusercontent.com
-------
The latest is ok also.
