### ISSUE TITLE
cannot change download path

### ISSUE THREAD

**Issue by arr111** [Suwayomi/docker-tachidesk#70]
why, each i change server download.path with /mnt/sda1/aa/db. after that, i run tachidesk and i saw the log always reset to default server download.path = ""

i run the tachidesk on aarch64

![Screenshot_2024-01-08-18-38-25-124_com opera browser](https://github.com/Suwayomi/docker-tachidesk/assets/126553612/0c906009-981e-4019-9b5d-ec8ebecd2223)
![Screenshot_2024-01-08-18-38-07-571_com opera browser](https://github.com/Suwayomi/docker-tachidesk/assets/126553612/ab602f45-9516-49c4-a77d-9cef6759cb59)

**Comment by Syer10** [comment]
The docker image doesn't support the downloads config, this is intentional
