### ISSUE TITLE
Settings retention

### ISSUE THREAD

**Issue by Kickunio** [Suwayomi/docker-tachidesk#71]
As some settings don't have environmental variables (i.e. skip updating entries), every update those settings are reset and have to be changed again.
It would be nice if there was another possibility to save settings outside of environment variables to store some of the settings

**Comment by Syer10** [comment]
All settings should have env variables though? What setting do you mean by `skip updating entries`?

**Comment by Kickunio** [comment]
![image](https://github.com/Suwayomi/docker-tachidesk/assets/83494636/f4fab654-2b24-42ac-801e-cbd7f14f754f)
It's in library settings - every restart it goes back to default and I don't see env variables in readme to set those up

**Comment by Syer10** [comment]
Those are included with 3 variables, `UPDATE_EXCLUDE_UNREAD` , `UPDATE_EXCLUDE_STARTED`, and `UPDATE_EXCLUDE_COMPLETED`

**Comment by Kickunio** [comment]
Ok, didn't see that - at first I thought it would be one setting, didn't think it would be three.
Closing Issue
