### ISSUE TITLE
Support alternative user/group (UID/GID)

### ISSUE THREAD

**Issue by chancez** [Suwayomi/docker-tachidesk#72]
I'd like to run the container with an alternative user/group similar to most linuxserver.io docker images. The main reason is it lets me ensure that different containers can all access files created or managed by other containers. For example komga runs with uid 99 and GID 100 but tachidesk runs with 1000, so komga cannot read the files tachidesk creates.

**Comment by Syer10** [comment]
Feel free to open a PR. Our old docker dev that this was the standard but I feel like its just been causing us issues

**Comment by chancez** [comment]
@Syer10 Would you be open to using the Linuxserver.io base image? https://github.com/linuxserver/docker-baseimage-ubuntu

The Dockerfile would be similar to this one https://github.com/linuxserver/docker-unifi-controller/blob/master/Dockerfile (which is another application written in Java using their base image)

**Comment by Syer10** [comment]
What platforms does the linuxserver base image support? I don't want to cut too many platforms out

**Comment by chancez** [comment]
Ah good point. Only amd64/arm64 I think, and as far as I can tell, they're not multi-arch images either which is a bit annoying too. I have built images that support arbitrary UID/GIDs myself too, but I'd have to remember how to do it.
