### ISSUE TITLE
Settings saved to server.conf gets rewritten on restart after accessing given setting

### ISSUE THREAD

**Issue by dm0red** [Suwayomi/docker-tachidesk#78]
# issue
Settings saved to server.conf gets rewritten on restart after accessing given setting

# steps to reproduce
1. As example - change "Download location" in /settings/downloadSettings
2. restart container
3. Access /settings/downloadSettings again, "Download location" will be empty again

# env
v0.7.0-r1466

**Comment by Syer10** [comment]
Download location is not supported. Create a specific volume for downloads and put it before your normal volume.

**Comment by dm0red** [comment]
But that's not the point here, as stated in the title - settings are being overwritten on restarts. "Download location" setting was just an example. The same happens for example for "Parallel source requests"

**Comment by Syer10** [comment]
@schroda can you verify?

**Comment by schroda** [comment]
no, the only way I can think of, why this is happening, is if it is used without a volume, because then obviously the server.conf gets created from scratch on every start

**Comment by dm0red** [comment]
hmm... I would swear on my right hand that it did not work, but can't reproduce it now.
My bad, sorry for stealing your time!
