### ISSUE TITLE
Unable to Add Extensions OR Enable Languages in Extensions

### ISSUE THREAD

**Issue by jaminW55** [Suwayomi/docker-tachidesk#83]
I have tried mounting directly to a directory, and using non-persistent mode a few times each, and each time I am unable to add extensions or select languages to enable. 
Is there a specific command or config file somewhere I am supposed to edit to enable this feature? I do not see instructions for such actions posted.

![image](https://github.com/Suwayomi/docker-tachidesk/assets/133602605/0ea627a5-fbf4-46c2-a0ec-3c4bf90eb436)

**Comment by Syer10** [comment]
Hey! Suwayomi does not include any extension repos by default after the Tachiyomi repo was shut down. You can add your own using the `EXTENSION_REPOS` environment variable, please read the README for the format you need to use.

Make sure to install the preview image of Suwayomi and find an extensions repo, you have to use google to find a Tachiyomi extension repo.

**Comment by jaminW55** [comment]
So I need to receive said APK from the extensions_repos and then install internally within the container?
Very different than my last setup!

**Comment by Syer10** [comment]
Nope, you need to find a extensions repo on your own and then pass the url in a specific format through the environment variable. Then Suwayomi will use that repo as the source of extensions and updates
