### ISSUE TITLE
Environment variables do not take effect on unraid.

### ISSUE THREAD

**Issue by shanyan-wcx** [Suwayomi/docker-tachidesk#86]
I have configured these items:
SOCKS_PROXY_ENABLED
SOCKS_PROXY_HOST
SOCKS_PROXY_PORT
DOWNLOAD_AS_CBZ
WEB_UI_FLAVOR
EXTENSION_REPOS
They have not taken effect.

**Comment by Syer10** [comment]
Make sure you are using the preview tag, otherwise this sounds like a Unraid bug.
