### ISSUE TITLE
[BUG] Opening tachidesk only shows white screen. 

### ISSUE THREAD

**Issue by pjpm15** [Suwayomi/docker-tachidesk#9]
---

## Device information
- Tachidesk docker version: 0.6.3 and 0.6.3 preview
- Server Operating System: Ubuntu 20.04
- Server Desktop Environment: N/A

## Steps to reproduce
1. Update using docker-compose.

### Expected behavior
Should show the tachidesk home screen.

### Actual behavior
Just show a white screen.

## Other details
Tried to install using docker-compose and docker run, but same results.  Downgrading to 0.6.2 works.

**Comment by arbuilder** [comment]
Then it is an issue with the newer tachidesk jar and for fixing this issue you need to create an issue on tachidesk repo
